### PR TITLE
getJob(long) on a non existing job now throw a JqmInvalidRequestException

### LINKED ISSUE #640: JdbcClient.getJob(long) IndexOutOfBoundsException when job does not exist
It should instead return a JqmInvalidRequestException. Otherwise error handling of all users (inclusing the JersyClient) cannot work reliably.

### PR DESCRIPTION
**Pull request by cyprien-enioka**
fix #640

### CODE REVIEW

File: jqm-all/jqm-api-client/jqm-api-client-jdbc/src/main/java/com/enioka/jqm/client/jdbc/api/JdbcClient.java [hunk 1]
```diff
@@ -1383,60 +1383,11 @@ private com.enioka.jqm.client.api.JobInstance getJob(ResultSet rs, DbConn cnx) t
...
-        // {
-        // throw new JqmClientException("an error occured during query execution", e);
-        // }
-        // finally
-        // {
-        // closeQuietly(em);
-        // }
+        try{
+            return this.newQuery().setJobInstanceId(idJob).setQueryHistoryInstances(true).setQueryLiveInstances(true).invoke().get(0);
+        } catch (Exception e) {
```
Comment (Pauleing) [inline jqm-all/jqm-api-client/jqm-api-client-jdbc/src/main/java/com/enioka/jqm/client/jdbc/api/JdbcClient.java]: This will cover up any other issue by pretending it's a job not found problem. 
You should just put the result of invoke in a variable, throw the exception if the list is empty and return get(0) otherwise

**Review by Pauleing — CHANGES_REQUESTED** [review]
You should only use broad Exception catch when there is no other option.
